//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kozolovich123
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        public int Id { get; set; }
        public string tree_type { get; set; }
        public string habitat { get; set; }
        public string life_span { get; set; }
    }
}
